name: currency_calc
description: Currency Calculator by tnsoftbear
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.5
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true # Enable generation of localized Strings from arb files.