apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: nginx-ns
data:
  param1: value1
  nginx.conf: |
    server {
        listen       80 default_server;
        server_name  _;
        default_type text/plain;
        location / {
            return 200 '$hostname\n';
        }
    }
  param2: value2