apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: nginx-ns
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    env:
    - name: APP_NAME
      value: "nginx-app"
    envFrom:
    - configMapRef:
        name: nginx-configmap-2
    volumeMounts:
    - name: nginx-configmap-volume
      mountPath: /etc/nginx/conf.d/
  volumes:
  - name: nginx-configmap-volume
    configMap:
      name: nginx-configmap
