apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-nfs-server-provisioner-0
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/srv/volumes/data-nfs-server-provisioner-0"
  claimRef:
    namespace: nfs
    name: data-nfs-server-provisioner-0