# ansible-playbook --user igor -i ./inventory.ini del-user-uninstall-curl.yml

---
- name: Rollback configuration
  hosts: bern_vm1
  become: true
  vars:
    ansible_become_password: "x"

  tasks:
    - name: Remove user
      ansible.builtin.user:
        name: ansibleuser
        state: absent

    - name: Remove curl
      ansible.builtin.apt:
        name: curl
        state: absent
