apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: alpine:latest
          command: ['sh', '-c', 'while true; do echo "logging" >> /opt/logs.txt; sleep 1; done']
          volumeMounts:
            - name: data
              mountPath: /opt
      initContainers:
        - name: logshipper
          image: alpine:latest
          restartPolicy: Always
          command: ['sh', '-c', 'tail -F /opt/logs.txt']
          volumeMounts:
            - name: data
              mountPath: /opt
          startupProbe:
            exec:
              command:
              - ls
            initialDelaySeconds: 30
        - name: myjob2
          image: alpine:latest
          command: ['sh', '-c', 'echo "logging" >> /opt/logs.txt']
        - name: myjob3
          image: alpine:latest
          command: ['sh', '-c', 'echo "logging" >> /opt/logs.txt']
      volumes:
        - name: data
          emptyDir: {}