---
# vars file for mariadb
mariadb_var:
  apt:
    packages:
      - apt-transport-https
      - curl
    keyring:
      dir:
        path: '/etc/apt/keyrings'
        permissions: '0755'
      file:
        name: 'mariadb-keyring.pgp'
        permissions: '0644'
      key_url: 'https://mariadb.org/mariadb_release_signing_key.pgp'
    sources_file_path: '/etc/apt/sources.list'
    repo_info: |
      deb [signed-by=/etc/apt/keyrings/mariadb-keyring.pgp] https://mariadb.mirror.serveriai.lt/repo/11.4/debian bookworm main
...
