---
init_var:
  apt:
    sources_file:
      path: '/etc/apt/sources.list'
      permissions: '0644'
    packages:
      - sudo
      - vim
      - mc
  sshd:
    config_file_path: '/etc/ssh/sshd_config'
...
