---
- name: Restart systemd-timesyncd service
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted

- name: Replace /etc/apt/sources.list with custom sources.list
  ansible.builtin.copy:
    src: sources.list
    dest: "{{ init_var.apt.sources_file.path }}"
    owner: root
    group: root
    mode: "{{ init_var.apt.sources_file.permissions }}"
    backup: false

- name: Install packages
  ansible.builtin.apt:
    name: "{{ init_var.apt.packages }}"
    update_cache: true
    state: present

- name: Generate password hash
  ansible.builtin.command: "openssl passwd -6 {{ init_def.user.password }}"
  register: password_hash
  changed_when: password_hash.rc != 0

- name: Create user 'ansible' and add to 'sudo' group
  ansible.builtin.user:
    name: "{{ init_def.user.name }}"
    groups: "{{ init_def.user.groups }}"
    append: true
    shell: "{{ init_def.user.shell }}"
    password: "{{ password_hash.stdout }}"
    state: present

- name: Upload SSH public key for ansible user
  ansible.posix.authorized_key:
    user: "{{ init_def.user.name }}"
    key: "{{ lookup('file', init_def.user.ssh_public_key_path) }}"
    state: present

- name: Disable root SSH login
  ansible.builtin.lineinfile:
    path: "{{ init_var.sshd.config_file_path }}"
    regexp: '^PermitRootLogin yes'
    line: 'PermitRootLogin no'
  notify:
    - Restart SSH service
...
