---
# tasks file for mariadb
- name: Restart systemd-timesyncd service
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted

- name: Install packages (apt-transport-https, curl)
  ansible.builtin.apt:
    name: "{{ mariadb_var.apt.packages }}"
    update_cache: true
    state: present

- name: Create the directory /etc/apt/keyrings
  ansible.builtin.file:
    path: "{{ mariadb_var.apt.keyring.dir.path }}"
    mode: "{{ mariadb_var.apt.keyring.dir.permissions }}"
    state: directory

- name: Download the MariaDB release signing key
  ansible.builtin.get_url:
    url: "{{ mariadb_var.apt.keyring.key_url }}"
    dest: "{{ mariadb_var.apt.keyring.dir.path }}/{{ mariadb_var.apt.keyring.file.name }}"
    mode: "{{ mariadb_var.apt.keyring.file.permissions }}"

- name: Add MariaDB Lithuanian APT repository
  ansible.builtin.blockinfile:
    path: "{{ mariadb_var.apt.sources_file_path }}"
    insertafter: EOF
    block: "{{ mariadb_var.apt.repo_info }}"

- name: Install MariaDB
  ansible.builtin.apt:
    name: mariadb-server
    update_cache: true
    autoclean: true
    autoremove: true
    state: present
...
