# ansible-playbook --user igor -i ./inventory.ini add-user-install-curl.yml

- name: Add user and install curl
  hosts: bern_vm1
  tasks:
    - name: Preconfig block
      become: true
      vars:
        ansible_become_password: "x"
      block:

        - name: Create user
          vars:
            username: ansibleuser
          ansible.builtin.user:
            name: "{{ username }}"
            state: present
            shell: /bin/bash
            home: /home/{{ username }}
            comment: "Ansible user"

        - name: Install curl
          ansible.builtin.apt:
            name: curl
            update-cache: true
...
