apiVersion: batch/v1
kind: CronJob
metadata:
  name: time-file-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: time-file-container
            image: busybox
            command: ["/bin/sh", "-c", "date > /tmp/$(date +'%Y-%m-%d_%H-%M-%S').txt"]
          restartPolicy: OnFailure
