# ansible-playbook -k full.yml
---
- name: Bootstrap VM
  hosts: bern_vm1
  become: true
  become_user: root       # sudo -u <become_user> -i
  remote_user: root       # ssh <remote_user>@host
  roles:
    - init
    - mariadb
...
