app:
  host: "0.0.0.0"
  port: 4000
  name: "News Service"
  server_header: "News Service Test Task"
auth:
  jwt:
    expiration: "10h"
    tokenkey: "must_be_secret"
mysql_storage:
  host: "localhost"
  port: 3307
  username: "admin"
  password: "123"
  database: "frr"
