apiVersion: apps/v1
kind: Deployment
metadata:
  name: space-station
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spstlbl
  template:
    metadata:
      labels:
        app: spstlbl
    spec:
      containers:
      - name: space-station
        image: space-station:local
        imagePullPolicy: Never
