# ansible-playbook -k init.yml
---
- name: Bootstrap VM
  hosts: bern_vm1
  become: true
  remote_user: root
  tasks:

    - name: Restart systemd-timesyncd service
      ansible.builtin.systemd:
        name: systemd-timesyncd
        state: restarted

    - name: Add APT repositories
      ansible.builtin.blockinfile:
        path: /etc/apt/sources.list
        insertafter: EOF
        block: |
          deb http://deb.debian.org/debian/ bookworm main
          deb http://security.debian.org/ bookworm-security main
          deb http://deb.debian.org/debian/ bookworm-updates main

    - name: Remove CD-ROM repository
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        regexp: '^deb cdrom'
        state: absent

    - name: Install packages (sudo, vim)
      ansible.builtin.apt:
        name:
          - sudo
          - vim
        update_cache: true
        state: present

    - name: Generate password hash
      ansible.builtin.command: "openssl passwd -6 a"
      register: password_hash
      changed_when: password_hash.rc != 0

    - name: Create user 'ansible' and add to 'sudo' group
      ansible.builtin.user:
        name: ansible
        groups: sudo
        append: true
        shell: /bin/bash
        password: "{{ password_hash.stdout }}"
        state: present

    - name: Upload SSH public key for ansible user
      ansible.posix.authorized_key:
        user: ansible
        key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
        state: present

    - name: Disable root SSH login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin yes'
        line: 'PermitRootLogin no'
      notify:
        - Restart SSH service

  handlers:
    - name: Restart SSH service
      ansible.builtin.service:
        name: ssh
        state: restarted
...
