services:
  app:
    build: 
      context: .
      dockerfile: ./infra/docker/app/Dockerfile
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis:6379
  redis:
    image: redis
    ports:
      - 6379:6379