services:
  app:
    build: 
      context: .
      dockerfile: ./infra/docker/app/Dockerfile
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis:6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 5s
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - 6379:6379