refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  file:
    kind: file
    path: "log/stderr.log"
    encoder:
      kind: json
root:
  level: info
  appenders:
    - stdout
    - file
