[package]
name = "screenshot"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
mockall = "0.12.1"
rdev = { version = "0.5.3", features = ["unstable_grab"] }
screenshots = "0.8.10"
