# ansible-playbook --user ansible -K -i ./inventory.ini db.yml
---
- name: "Install MariaDB"
  hosts: bern_vm1
  become: true
  tasks:

    - name: Restart systemd-timesyncd service
      ansible.builtin.systemd:
        name: systemd-timesyncd
        state: restarted

    - name: Install packages (apt-transport-https, curl)
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - curl
        state: present
        update_cache: true

    - name: Create the directory /etc/apt/keyrings
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download the MariaDB release signing key
      ansible.builtin.get_url:
        url: 'https://mariadb.org/mariadb_release_signing_key.pgp'
        dest: /etc/apt/keyrings/mariadb-keyring.pgp
        mode: '0644'

    - name: Add MariaDB Lithuanian APT repository
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        insertafter: EOF
        line: deb [signed-by=/etc/apt/keyrings/mariadb-keyring.pgp] https://mariadb.mirror.serveriai.lt/repo/11.4/debian bookworm mai

    - name: Install MariaDB
      ansible.builtin.apt:
        name: mariadb-server
        state: present
        update_cache: true
        autoclean: true
        autoremove: true
...
