name: Different checks, test and verifications

on:
  push:
    branches: [ main ]

jobs:
  check:
    name: Check modifications
    outputs:
      go_exercism_two-fer: ${{ steps.check_files.outputs.go_exercism_two-fer }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: check modified fields
        id: check_files
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD

          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file; do
            echo $file
            if [[ $file == go/exercism/two-fer/* ]]; then
              echo "::set-output name=go_exercism_two-fer::true"
            # elif [[ $file == /* ]]; then
            #   echo "::set-output name=...::true"
            else
              echo "file does not belong to any check pattern"
            fi
          done < files.txt
  
  go_exercism_two-fer:
    needs: check
    if: needs.check.outputs.go_exercism_two-fer == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Set up go 1.x
      uses: actions/setup-go@v5.0.2
      with:
        go-version: ^1.22
  
    - uses: actions/checkout@v4.1.7

    - name: Run test
      run: cd go/exercism/two-fer/ && go test .