name: Different checks, test and verifications

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check:
    name: Check modifications
    outputs:
      go_exercism_two-fer: ${{ steps.check_files.outputs.go_exercism_two-fer }}
      go_own_sys-dev_signal_ex1: ${{ steps.check_files.outputs.go_own_sys-dev_signal_ex1 }}
      k8s_healthprobe-for-app_k8s: ${{ steps.check_files.outputs.k8s_healthprobe-for-app_k8s }}
      ansible_bern-vm: ${{ steps.check_files.outputs.ansible_bern-vm }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2         # Клонируем 2 последних коммита
      
      - name: check modified fields
        id: check_files
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD

          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file; do
            echo $file
            if [[ $file == go/exercism/two-fer/* ]]; then
              echo "go_exercism_two-fer=true" >> $GITHUB_OUTPUT
            elif [[ $file == go/own/sys-dev/signal_ex1/* ]]; then
              echo "go_own_sys-dev_signal_ex1=true" >> $GITHUB_OUTPUT
            elif [[ $file == k8s/healthprobe-for-app/k8s/* ]]; then
              echo "k8s_healthprobe-for-app_k8s=true" >> $GITHUB_OUTPUT
            elif [[ $file == ansible/bern-vm/* ]]; then
              echo "ansible_bern-vm=true" >> $GITHUB_OUTPUT
            else
              echo "file $file does not belong to any check pattern"
            fi
          done < files.txt

          if [ -s "$GITHUB_OUTPUT" ]; then
            echo "### :rocket: Expected jobs:" >> $GITHUB_STEP_SUMMARY
            cat $GITHUB_OUTPUT >> $GITHUB_STEP_SUMMARY
          fi

  go_exercism_two-fer:
    needs: check
    if: needs.check.outputs.go_exercism_two-fer == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Set up go 1.x
      uses: actions/setup-go@v5.0.2
      with:
        go-version: ^1.22
  
    - uses: actions/checkout@v4.1.7

    - name: Run test
      run: cd go/exercism/two-fer/ && go test .

    - name: Summary job
      run: echo "- go/exercism/two-fer code is tested" >> $GITHUB_STEP_SUMMARY

  go_own_sys-dev_signal_ex1:
    needs: check
    if: needs.check.outputs.go_own_sys-dev_signal_ex1 == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
            context: "{{defaultContext}}:go/own/sys-dev/signal_ex1"
            file: ./Dockerfile
            push: true
            tags: ghcr.io/${{ github.actor }}/go-own-sys-dev-signal-ex1:latest

      - name: Summary job
        run: echo "- go/own/sys-dev/signal_ex1 build is published" >> $GITHUB_STEP_SUMMARY
      
    # Паблишинг в docker.io репозиторий
    # Не работает, фейлится с "401 Unauthorized" на шаге "Build and push"
    # steps:
    #   - name: Set up QEMU
    #     uses: docker/setup-qemu-action@v3
      
    #   - name: Set up Docker Buildx
    #     uses: docker/setup-buildx-action@v3
  
    #   - name: Login to Docker Hub
    #     uses: docker/login-action@v3
    #     with:
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}
    #       logout: false
  
    #   - name: Build and push
    #     uses: docker/build-push-action@v6
    #     with:
    #       context: "{{defaultContext}}:go/own/sys-dev/signal_ex1"
    #       file: ./Dockerfile
    #       push: true
    #       tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-own-sys-dev-signal-ex1:latest

  k8s_healthprobe-for-app_k8s:
    needs: check
    if: needs.check.outputs.k8s_healthprobe-for-app_k8s == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: login to Github Packages
        run: echo "${{ github.token }}" | docker login https://ghcr.io -u ${GITHUB_ACTOR} --password-stdin
      - uses: actions/checkout@v4
      - uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          entrypoint: '/kubeconform'
          args: "-summary -output json k8s/healthprobe-for-app/k8s/"

  ansible_bern-vm:
    needs: check
    if: needs.check.outputs.ansible_bern-vm == 'true'
    name: Ansible Lint for bern-vm project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          args: ""
          setup_python: "true"
          working_directory: "./ansible/bern-vm"
          requirements_file: "tests/requirements.yml"