name: Different checks, test and verifications

on:
  push:
    branches: [ main ]

jobs:
  check:
    name: Check modifications
    outputs:
      go_exercism_two-fer: ${{ steps.check_files.outputs.go_exercism_two-fer }}
      go_own_sys-dev_signal_ex1: ${{ steps.check_files.outputs.go_own_sys-dev_signal_ex1 }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2         # Клонируем 2 последних коммита
      
      - name: check modified fields
        id: check_files
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD

          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file; do
            echo $file
            if [[ $file == go/exercism/two-fer/* ]]; then
              echo "go_exercism_two-fer=true" >> $GITHUB_OUTPUT
            elif [[ $file == go/own/sys-dev/signal_ex1/* ]]; then
              echo "go_own_sys-dev_signal_ex1=true" >> $GITHUB_OUTPUT
            else
              echo "file $file does not belong to any check pattern"
            fi
          done < files.txt
          echo "=============== GITHUB_OUTPUT ==============="
          echo "::debug::GITHUB_OUTPUT is $GITHUB_OUTPUT"
          cat $GITHUB_OUTPUT
          echo "::group::My title"
          echo "Inside group"
          echo "Inside group too"
          echo "::add-mask::Mona The Octocat"
          echo "::endgroup::"
          echo "GITHUB_OUTPUT: ::add-mask::$GITHUB_OUTPUT"

  go_exercism_two-fer:
    needs: check
    if: needs.check.outputs.go_exercism_two-fer == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Set up go 1.x
      uses: actions/setup-go@v5.0.2
      with:
        go-version: ^1.22
  
    - uses: actions/checkout@v4.1.7

    - name: Run test
      run: cd go/exercism/two-fer/ && go test .
    
  go_own_sys-dev_signal_ex1:
    needs: check
    if: needs.check.outputs.go_own_sys-dev_signal_ex1 == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
            context: "{{defaultContext}}:go/own/sys-dev/signal_ex1"
            file: ./Dockerfile
            push: true
            tags: ghcr.io/${{ github.actor }}/go-own-sys-dev-signal-ex1:latest

    # Паблишинг в docker.io репозиторий
    # Не работает, фейлится с "401 Unauthorized" на шаге "Build and push"
    # steps:
    #   - name: Set up QEMU
    #     uses: docker/setup-qemu-action@v3
      
    #   - name: Set up Docker Buildx
    #     uses: docker/setup-buildx-action@v3
  
    #   - name: Login to Docker Hub
    #     uses: docker/login-action@v3
    #     with:
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}
    #       logout: false
  
    #   - name: Build and push
    #     uses: docker/build-push-action@v6
    #     with:
    #       context: "{{defaultContext}}:go/own/sys-dev/signal_ex1"
    #       file: ./Dockerfile
    #       push: true
    #       tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-own-sys-dev-signal-ex1:latest
